name: Deploy to GitHub Pages
on:
  push:
    branches: [fix-web-blank] # Or your main branch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"

      - name: Setup Expo
        uses: expo/expo-github-action@v8
        with:
          expo-version: latest
          token: ${{ secrets.EXPO_TOKEN }} # Only needed if using EAS

      - name: Install dependencies
        run: npm install

      # - name: Build Web
      #   run: |
      #     npx expo export --platform web --clear
      #     # Force the path in index.html
      #     sed -i 's|src="/_expo|src="/tafe.labApi/_expo|g' dist/index.html
      #     # TELL GITHUB NOT TO IGNORE THE _EXPO FOLDER
      #     touch dist/.nojekyll
      - name: Build Web
        run: |
          EXPO_USE_STATIC=false npx expo export --platform web --clear
          sed -i 's|src="/_expo|src="/tafe.labApi/_expo|g' dist/index.html
          find dist/_expo/static/js/web -name "*.js" -exec sed -i 's|"/assets/|"/tafe.labApi/assets/|g' {} +
          touch dist/.nojekyll

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist # Expo 54 exports to 'dist' by default
          branch: gh-pages

# 1. Build the app (ignoring the expo-router error)
# EXPO_USE_STATIC=false npx expo export --platform web --clear
# # 2. Fix the HTML paths (the script tag you see at the bottom)
# sed -i 's|src="/_expo|src="/tafe.labApi/_expo|g' dist/index.html
# # 3. Fix the Internal Asset paths (MaterialIcons and Fonts)
# # This finds any mention of "/assets/" in your JS and adds the prefix
# find dist/_expo/static/js/web -name "*.js" -exec sed -i 's|"/assets/|"/tafe.labApi/assets/|g' {} +
# # 4. Tell GitHub NOT to hide the _expo folder
# touch dist/.nojekyll
