name: Deploy to GitHub Pages
on:
  push:
    branches: [fix-web-blank] # Or your main branch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"

      - name: Setup Expo
        uses: expo/expo-github-action@v8
        with:
          expo-version: latest
          token: ${{ secrets.EXPO_TOKEN }} # Only needed if using EAS

      - name: Install dependencies
        run: npm install

      # - name: Build Web
      #   run: |
      #     npx expo export --platform web --clear
      #     # Force the path in index.html
      #     sed -i 's|src="/_expo|src="/tafe.labApi/_expo|g' dist/index.html
      #     # TELL GITHUB NOT TO IGNORE THE _EXPO FOLDER
      #     touch dist/.nojekyll
      - name: Build Web
        run: |
          # 1. Build the app
          EXPO_USE_STATIC=false npx expo export --platform web --clear

          # 2. Fix the HTML script tags
          sed -i 's|src="/_expo|src="/tafe.labApi/_expo|g' dist/index.html

          # 3. Fix the Manifest/JSON paths
          sed -i 's|href="/|href="/tafe.labApi/|g' dist/index.html

          # 4. FIX THE ICONS & INTERNAL JS (This fixes the (index):1 error)
          # This replaces /assets/ and /_expo/ inside the JS code itself
          find dist/_expo/static/js/web -name "*.js" -exec sed -i 's|"/assets/|"/tafe.labApi/assets/|g' {} +
          find dist/_expo/static/js/web -name "*.js" -exec sed -i 's|"/_expo/|"/tafe.labApi/_expo/|g' {} +

          # 5. Prevent GitHub from hiding folders
          touch dist/.nojekyll

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist # Expo 54 exports to 'dist' by default
          branch: gh-pages
